version: '3.9'

services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    user: '1000:1000' # run as non-root user
    ports:
      - '5000:5000'
    volumes:
      - auth_logs:/app/logs
    restart: unless-stopped

volumes:
  auth_logs:

